### ISSUE TITLE
Backend ToDo

### ISSUE THREAD

**Issue by Philogag** [Philogag/Flask-HDFS-Cloud-Disk#3]
+ Auth
    + [x] login
    + [x] logout
    + [x] check_login
    + [x] regist
+ FileSystem
    + [x] list
    + [x] mkdir
    + [x] cd
    + [x] move
    + [x] rename
+ ReCycle
    + [ ] add
    + [ ] auto TTL on mongo,hdfs & hbase
    + [ ] list
    + [ ] return
+ Share
    + [ ] make share task
    + [ ] share TTL
    + [ ] share password
    + [ ] manamge my share
    + [ ] add share into my cloud
+ IO
    + [x] start upload task
    + [x] upload chunk
    + [x] endof upload task
    + [x] download chunk
